import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { isMobile } from 'react-device-detect';
import "./globals.css";
import '@haeahn-design/core/style.css'

// import { logger, adminLogger } from '@/libs/logger';

import Provider from './provider';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "HUB 매뉴얼",
  // description: "Generated by create next app",
  openGraph: {
    title: 'HUB 매뉴얼',
    // images: ['/og.png'],
  },
};

// design system config
// import { config, getValidation } from '@haeahn-design/core';
import { config } from '@haeahn-design/core';

import Header from '@/components/layout/header/header';
import Navigation from '@/components/layout/navigation';

// config({
//   licenseKey: process.env.HAEAHN_DESIGN_SYSTEM_API_KEY || '',
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 필요한 경우에만 로깅 (예: 초기화, 에러 등)
  // logger.info({ msg: 'RootLayout rendered' });
  
  const className = isMobile ? 'ha_design ha_design_mobile' : 'ha_design ha_design_web';
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}></body> */}
      <body className={`${className}`}>
        <Provider>
          <header>
            <Header />
          </header>

          <main>
            <div className="left-sidebar-container">
              <Navigation />
            </div>

            <div className="right-sidebar-container"></div>

            <div className="content-container">
              {children}
            </div>
          </main>
          {/* <Footer /> */}
          
        </Provider>
      </body>
    </html>
  );
}
